#ifndef CTRE__PCRE__HPP
#define CTRE__PCRE__HPP

// THIS FILE WAS GENERATED BY TABLEWRIGHT TOOL, DO NOT MODIFY THIS FILE

#include "../ctll/grammars.hpp"

namespace ctre {

struct pcre {

	// NONTERMINALS:
	struct S {}; using _start = S;
	struct alphanum_characters_push_name_anon {};
	struct asserts {};
	struct atom {};
	struct atom_in_capture {};
	struct atom_repeat {};
	struct atom_repeat_in_capture {};
	struct backslash {};
	struct backslash_g {};
	struct backslash_g_angle_open {};
	struct backslash_g_apostrophe {};
	struct backslash_g_copen {};
	struct backslash_range {};
	struct backslash_range_c {};
	struct backslash_range_u {};
	struct backslash_range_x {};
	struct backslash_set {};
	struct block {};
	struct block_name {};
	struct block_questionmark {};
	struct block_questionmark_P {};
	struct block_questionmark_angle_open {};
	struct callout_dq_chars_push_name_anon {};
	struct callout_kind {};
	struct callout_sq_chars_push_name_anon {};
	struct character {};
	struct character_class {};
	struct character_class_sopen {};
	struct character_in_capture {};
	struct class_named {};
	struct class_named_name {};
	struct class_named_name_a {};
	struct class_named_name_a_l {};
	struct class_named_name_p {};
	struct class_named_sopen {};
	struct class_named_sopen_colon {};
	struct comment_body {};
	struct comment_chars_anon {};
	struct condition {};
	struct condition_branch {};
	struct condition_branches {};
	struct condition_branches_end {};
	struct condition_questionmark {};
	struct condition_questionmark_angle_open {};
	struct content {};
	struct content2 {};
	struct content2_pipe {};
	struct content_in_capture {};
	struct content_or_empty {};
	struct hexdec_push_hexdec_anon {};
	struct mod {};
	struct mode_switch {};
	struct mode_switch2 {};
	struct num_push_number_anon {};
	struct number {};
	struct octal_push_octal_anon {};
	struct octal_suffix {};
	struct octal_suffix2 {};
	struct opt_content {};
	struct preblock {};
	struct property_name {};
	struct property_name2 {};
	struct property_value {};
	struct range {};
	struct range_minus {};
	struct repeat {};
	struct repeat_copen {};
	struct repeat_copen_number {};
	struct repeat_copen_number_comma {};
	struct set {};
	struct set2a {};
	struct set2b {};
	struct set_push_property_value_anon {};
	struct setitem {};
	struct setitem2 {};
	struct setitem2_backslash {};
	struct setitem_backslash {};
	struct string {};
	struct string2 {};
	struct string_in_capture {};

	// 'action' types:
	struct class_digit: ctll::action {};
	struct class_horizontal_space: ctll::action {};
	struct class_named_alnum: ctll::action {};
	struct class_named_alpha: ctll::action {};
	struct class_named_ascii: ctll::action {};
	struct class_named_blank: ctll::action {};
	struct class_named_cntrl: ctll::action {};
	struct class_named_digit: ctll::action {};
	struct class_named_graph: ctll::action {};
	struct class_named_lower: ctll::action {};
	struct class_named_print: ctll::action {};
	struct class_named_punct: ctll::action {};
	struct class_named_space: ctll::action {};
	struct class_named_upper: ctll::action {};
	struct class_named_word: ctll::action {};
	struct class_named_xdigit: ctll::action {};
	struct class_non_horizontal_space: ctll::action {};
	struct class_non_vertical_space: ctll::action {};
	struct class_nondigit: ctll::action {};
	struct class_nonnewline: ctll::action {};
	struct class_nonspace: ctll::action {};
	struct class_nonword: ctll::action {};
	struct class_space: ctll::action {};
	struct class_vertical_space: ctll::action {};
	struct class_word: ctll::action {};
	struct create_hexdec: ctll::action {};
	struct create_number: ctll::action {};
	struct finish_hexdec: ctll::action {};
	struct look_finish: ctll::action {};
	struct make_alternate: ctll::action {};
	struct make_atomic: ctll::action {};
	struct make_back_reference: ctll::action {};
	struct make_callout: ctll::action {};
	struct make_callout_named: ctll::action {};
	struct make_callout_numbered: ctll::action {};
	struct make_capture: ctll::action {};
	struct make_capture_with_name: ctll::action {};
	struct make_comment: ctll::action {};
	struct make_condition_capture_ref: ctll::action {};
	struct make_condition_capture_ref_ahead: ctll::action {};
	struct make_condition_capture_ref_behind: ctll::action {};
	struct make_conditional_one: ctll::action {};
	struct make_conditional_two: ctll::action {};
	struct make_control_character: ctll::action {};
	struct make_grapheme_cluster: ctll::action {};
	struct make_lazy: ctll::action {};
	struct make_optional: ctll::action {};
	struct make_possessive: ctll::action {};
	struct make_property: ctll::action {};
	struct make_property_negative: ctll::action {};
	struct make_range: ctll::action {};
	struct make_relative_back_reference: ctll::action {};
	struct make_sequence: ctll::action {};
	struct make_subroutine_call: ctll::action {};
	struct make_subroutine_call_ahead: ctll::action {};
	struct make_subroutine_call_behind: ctll::action {};
	struct make_subroutine_call_with_name: ctll::action {};
	struct mode_case_insensitive: ctll::action {};
	struct mode_case_sensitive: ctll::action {};
	struct mode_multiline: ctll::action {};
	struct mode_singleline: ctll::action {};
	struct negate_class_named: ctll::action {};
	struct prepare_capture: ctll::action {};
	struct push_assert_begin: ctll::action {};
	struct push_assert_end: ctll::action {};
	struct push_assert_subject_begin: ctll::action {};
	struct push_assert_subject_end: ctll::action {};
	struct push_assert_subject_end_with_lineend: ctll::action {};
	struct push_character: ctll::action {};
	struct push_character_alarm: ctll::action {};
	struct push_character_anything: ctll::action {};
	struct push_character_escape: ctll::action {};
	struct push_character_formfeed: ctll::action {};
	struct push_character_newline: ctll::action {};
	struct push_character_return_carriage: ctll::action {};
	struct push_character_tab: ctll::action {};
	struct push_empty: ctll::action {};
	struct push_hexdec: ctll::action {};
	struct push_match_point_reset: ctll::action {};
	struct push_name: ctll::action {};
	struct push_not_word_boundary: ctll::action {};
	struct push_number: ctll::action {};
	struct push_octal: ctll::action {};
	struct push_property_name: ctll::action {};
	struct push_property_value: ctll::action {};
	struct push_word_boundary: ctll::action {};
	struct repeat_ab: ctll::action {};
	struct repeat_at_least: ctll::action {};
	struct repeat_exactly: ctll::action {};
	struct repeat_plus: ctll::action {};
	struct repeat_star: ctll::action {};
	struct reset_capture: ctll::action {};
	struct set_combine: ctll::action {};
	struct set_empty: ctll::action {};
	struct set_make: ctll::action {};
	struct set_make_negative: ctll::action {};
	struct set_start: ctll::action {};
	struct start_atomic: ctll::action {};
	struct start_lookahead_negative: ctll::action {};
	struct start_lookahead_positive: ctll::action {};
	struct start_lookbehind_negative: ctll::action {};
	struct start_lookbehind_positive: ctll::action {};

	// TERMINALS
	using _others = ctll::neg_set<'!','\"','#','$','&','\'','\x28','\x29','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','|','\x7D'>;
	using set_1 = ctll::set<'!','\"','#','$','&','\'','\x28',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using pipe = ctll::term<'|'>;
	using close = ctll::term<'\x29'>;
	using close__pipe = ctll::set<'\x29','|'>;
	using set_2 = ctll::set<'!','\"','#','&','\'',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','\\',']','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using dolar__caret = ctll::set<'$','^'>;
	using open = ctll::term<'\x28'>;
	using sopen = ctll::term<'['>;
	using cclose = ctll::term<'\x7D'>;
	using num = ctll::set<'0','1','2','3','4','5','6','7','8','9'>;
	using comma = ctll::term<','>;
	using set_3 = ctll::set<'!','\"','#','$','&','\'','\x28','\x29',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','|'>;
	using plus = ctll::term<'+'>;
	using star = ctll::term<'*'>;
	using questionmark = ctll::term<'?'>;
	using copen = ctll::term<'\x7B'>;
	using angle_close = ctll::term<'>'>;
	using equal_sign = ctll::term<'='>;
	using exclamation_mark = ctll::term<'!'>;
	using alpha_characters = ctll::set<'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using angle_open = ctll::term<'<'>;
	using apostrophe = ctll::term<'\''>;
	using c__i__m__s = ctll::set<'c','i','m','s'>;
	using colon = ctll::term<':'>;
	using P = ctll::term<'P'>;
	using hash = ctll::term<'#'>;
	using C = ctll::term<'C'>;
	using minus = ctll::term<'-'>;
	using ampersand = ctll::term<'&'>;
	using comment_chars = ctll::neg_set<'\x29'>;
	using callout_dq_chars = ctll::neg_set<'\"'>;
	using doublequote = ctll::term<'\"'>;
	using callout_sq_chars = ctll::neg_set<'\''>;
	using i = ctll::term<'i'>;
	using c = ctll::term<'c'>;
	using s = ctll::term<'s'>;
	using m = ctll::term<'m'>;
	using sclose = ctll::term<']'>;
	using set_4 = ctll::set<'!','\"','#','$','&','\'','\x28','\x29','*','+',',','.','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','|','\x7D'>;
	using caret = ctll::term<'^'>;
	using set_5 = ctll::set<'!','\"','#','$','&','\'','\x28','\x29','*','+',',','.','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\','^','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','|','\x7D'>;
	using a__b__c__d__g__l__p__s__u__w__x = ctll::set<'a','b','c','d','g','l','p','s','u','w','x'>;
	using u = ctll::term<'u'>;
	using h = ctll::term<'h'>;
	using a = ctll::term<'a'>;
	using n = ctll::term<'n'>;
	using p = ctll::term<'p'>;
	using l = ctll::term<'l'>;
	using t = ctll::term<'t'>;
	using r = ctll::term<'r'>;
	using k = ctll::term<'k'>;
	using g = ctll::term<'g'>;
	using o = ctll::term<'o'>;
	using w = ctll::term<'w'>;
	using e = ctll::term<'e'>;
	using d = ctll::term<'d'>;
	using b = ctll::term<'b'>;
	using x = ctll::term<'x'>;
	using set_6 = ctll::set<'\"','$','\x28','\x29','*','+','-','.','/','0','<','>','?','[','\\',']','^','a','c','e','f','n','o','r','t','u','x','\x7B','|','\x7D'>;
	using D__H__N__P__S__V__W__d__h__p__s__v__w = ctll::set<'D','H','N','P','S','V','W','d','h','p','s','v','w'>;
	using set_7 = ctll::set<'!','\"','#','$','&','\'','\x28','\x29','*','+',',','.','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','|','\x7D'>;
	using backslash_ = ctll::term<'\\'>;
	using set_8 = ctll::set<'!','\"','#','$','&','\'','\x28','\x29','*','+',',','.','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','^','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','|','\x7D'>;
	using set_9 = ctll::set<'!','\"','#','$','&','\'','\x28','\x29','*','+',',','.','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','|','\x7D'>;
	using hexdec = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','a','b','c','d','e','f'>;
	using set_10 = ctll::set<'?','@','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using octal = ctll::set<'0','1','2','3','4','5','6','7'>;
	using set_11 = ctll::set<'\"','$','\x28','\x29','*','+','-','.','/','<','>','?','[','\\',']','^','\x7B','|','\x7D'>;
	using d0 = ctll::term<'0'>;
	using f = ctll::term<'f'>;
	using set_12 = ctll::set<'!','\"','#','$','&','\'','\x28','\x29','*','+',',','-','.','/','8','9',':','<','=','>','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','|','\x7D'>;
	using D = ctll::term<'D'>;
	using W = ctll::term<'W'>;
	using N = ctll::term<'N'>;
	using S_ = ctll::term<'S'>;
	using v = ctll::term<'v'>;
	using V = ctll::term<'V'>;
	using H = ctll::term<'H'>;
	using A = ctll::term<'A'>;
	using z = ctll::term<'z'>;
	using Z = ctll::term<'Z'>;
	using B = ctll::term<'B'>;
	using K = ctll::term<'K'>;
	using X = ctll::term<'X'>;
	using escape_backreference = ctll::set<'1','2','3','4','5','6','7','8','9'>;
	using dot__alphanum_characters = ctll::set<'.','0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using set_13 = ctll::set<'!','\"','#','&','\'',',','-','/','0','1','2','3','4','5','6','7','8','9',':','<','=','>','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',']','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using dot = ctll::term<'.'>;
	using dolar = ctll::term<'$'>;
	using quote__close__comma__angle_close__cclose = ctll::set<'\'','\x29',',','>','\x7D'>;
	using alphanum_characters = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using quote__close__angle_close__cclose = ctll::set<'\'','\x29','>','\x7D'>;

	// (q)LL1 function:
	static constexpr auto rule(S, set_1) -> ctll::push<content>;
	static constexpr auto rule(S, _others) -> ctll::push<content>;
	static constexpr auto rule(S, ctll::epsilon) -> ctll::push<push_empty>;
	static constexpr auto rule(S, pipe) -> ctll::push<ctll::anything, push_empty, opt_content, make_alternate>;

	static constexpr auto rule(opt_content, ctll::epsilon) -> ctll::push<push_empty>;
	static constexpr auto rule(opt_content, set_1) -> ctll::push<content>;
	static constexpr auto rule(opt_content, _others) -> ctll::push<content>;

	static constexpr auto rule(content, set_1) -> ctll::push<string, content2>;
	static constexpr auto rule(content, _others) -> ctll::push<string, content2>;

	static constexpr auto rule(content_in_capture, set_1) -> ctll::push<string_in_capture, content2>;
	static constexpr auto rule(content_in_capture, _others) -> ctll::push<string_in_capture, content2>;
	static constexpr auto rule(content_in_capture, close) -> ctll::push<push_empty>;
	static constexpr auto rule(content_in_capture, pipe) -> ctll::push<ctll::anything, push_empty, content_or_empty, make_alternate>;

	static constexpr auto rule(content_or_empty, set_1) -> ctll::push<content>;
	static constexpr auto rule(content_or_empty, _others) -> ctll::push<content>;
	static constexpr auto rule(content_or_empty, close) -> ctll::push<push_empty>;

	static constexpr auto rule(content2_pipe, set_1) -> ctll::push<content, make_alternate>;
	static constexpr auto rule(content2_pipe, _others) -> ctll::push<content, make_alternate>;
	static constexpr auto rule(content2_pipe, close) -> ctll::push<push_empty, make_alternate>;
	static constexpr auto rule(content2_pipe, ctll::epsilon) -> ctll::push<push_empty, make_alternate>;

	static constexpr auto rule(content2, pipe) -> ctll::push<ctll::anything, content2_pipe>;
	static constexpr auto rule(content2, close) -> ctll::epsilon;
	static constexpr auto rule(content2, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(string, set_1) -> ctll::push<atom_repeat, string2>;
	static constexpr auto rule(string, _others) -> ctll::push<atom_repeat, string2>;

	static constexpr auto rule(string2, set_1) -> ctll::push<atom_repeat, string2, make_sequence>;
	static constexpr auto rule(string2, _others) -> ctll::push<atom_repeat, string2, make_sequence>;
	static constexpr auto rule(string2, close__pipe) -> ctll::epsilon;
	static constexpr auto rule(string2, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(string_in_capture, set_1) -> ctll::push<atom_repeat_in_capture, string2>;
	static constexpr auto rule(string_in_capture, _others) -> ctll::push<atom_repeat_in_capture, string2>;

	static constexpr auto rule(atom_repeat, set_1) -> ctll::push<atom, repeat>;
	static constexpr auto rule(atom_repeat, _others) -> ctll::push<atom, repeat>;

	static constexpr auto rule(atom_repeat_in_capture, set_1) -> ctll::push<atom_in_capture, repeat>;
	static constexpr auto rule(atom_repeat_in_capture, _others) -> ctll::push<atom_in_capture, repeat>;

	static constexpr auto rule(atom, set_2) -> ctll::push<character>;
	static constexpr auto rule(atom, _others) -> ctll::push<character>;
	static constexpr auto rule(atom, dolar__caret) -> ctll::push<asserts>;
	static constexpr auto rule(atom, open) -> ctll::push<preblock>;
	static constexpr auto rule(atom, sopen) -> ctll::push<character_class>;

	static constexpr auto rule(atom_in_capture, set_2) -> ctll::push<character_in_capture>;
	static constexpr auto rule(atom_in_capture, _others) -> ctll::push<character_in_capture>;
	static constexpr auto rule(atom_in_capture, dolar__caret) -> ctll::push<asserts>;
	static constexpr auto rule(atom_in_capture, open) -> ctll::push<preblock>;
	static constexpr auto rule(atom_in_capture, sopen) -> ctll::push<character_class>;

	static constexpr auto rule(repeat_copen_number_comma, cclose) -> ctll::push<repeat_at_least, ctll::anything, mod>;
	static constexpr auto rule(repeat_copen_number_comma, num) -> ctll::push<number, repeat_ab, cclose, mod>;

	static constexpr auto rule(repeat_copen_number, cclose) -> ctll::push<repeat_exactly, ctll::anything>;
	static constexpr auto rule(repeat_copen_number, comma) -> ctll::push<ctll::anything, repeat_copen_number_comma>;

	static constexpr auto rule(repeat_copen, num) -> ctll::push<number, repeat_copen_number>;

	static constexpr auto rule(repeat, set_3) -> ctll::epsilon;
	static constexpr auto rule(repeat, ctll::epsilon) -> ctll::epsilon;
	static constexpr auto rule(repeat, _others) -> ctll::epsilon;
	static constexpr auto rule(repeat, plus) -> ctll::push<ctll::anything, repeat_plus, mod>;
	static constexpr auto rule(repeat, star) -> ctll::push<ctll::anything, repeat_star, mod>;
	static constexpr auto rule(repeat, questionmark) -> ctll::push<ctll::anything, make_optional, mod>;
	static constexpr auto rule(repeat, copen) -> ctll::push<ctll::anything, repeat_copen>;

	static constexpr auto rule(mod, set_3) -> ctll::epsilon;
	static constexpr auto rule(mod, ctll::epsilon) -> ctll::epsilon;
	static constexpr auto rule(mod, _others) -> ctll::epsilon;
	static constexpr auto rule(mod, questionmark) -> ctll::push<ctll::anything, make_lazy>;
	static constexpr auto rule(mod, plus) -> ctll::push<ctll::anything, make_possessive>;

	static constexpr auto rule(number, num) -> ctll::push<ctll::anything, create_number, num_push_number_anon>;

	static constexpr auto rule(preblock, open) -> ctll::push<ctll::anything, prepare_capture, block>;

	static constexpr auto rule(block_questionmark_angle_open, equal_sign) -> ctll::push<ctll::anything, reset_capture, start_lookbehind_positive, content_in_capture, look_finish, close>;
	static constexpr auto rule(block_questionmark_angle_open, exclamation_mark) -> ctll::push<ctll::anything, reset_capture, start_lookbehind_negative, content_in_capture, look_finish, close>;
	static constexpr auto rule(block_questionmark_angle_open, alpha_characters) -> ctll::push<block_name, angle_close, content_in_capture, make_capture_with_name, close>;

	static constexpr auto rule(block_questionmark_P, angle_open) -> ctll::push<ctll::anything, block_name, angle_close, content_in_capture, make_capture_with_name, close>;
	static constexpr auto rule(block_questionmark_P, angle_close) -> ctll::push<ctll::anything, block_name, make_subroutine_call_with_name, close>;

	static constexpr auto rule(block_questionmark, c__i__m__s) -> ctll::push<mode_switch>;
	static constexpr auto rule(block_questionmark, angle_close) -> ctll::push<ctll::anything, reset_capture, start_atomic, content_in_capture, make_atomic, close>;
	static constexpr auto rule(block_questionmark, equal_sign) -> ctll::push<ctll::anything, reset_capture, start_lookahead_positive, content_in_capture, look_finish, close>;
	static constexpr auto rule(block_questionmark, angle_open) -> ctll::push<ctll::anything, block_questionmark_angle_open>;
	static constexpr auto rule(block_questionmark, exclamation_mark) -> ctll::push<ctll::anything, reset_capture, start_lookahead_negative, content_in_capture, look_finish, close>;
	static constexpr auto rule(block_questionmark, colon) -> ctll::push<ctll::anything, reset_capture, content_in_capture, close>;
	static constexpr auto rule(block_questionmark, P) -> ctll::push<ctll::anything, block_questionmark_P>;
	static constexpr auto rule(block_questionmark, apostrophe) -> ctll::push<ctll::anything, block_name, apostrophe, content_in_capture, make_capture_with_name, close>;
	static constexpr auto rule(block_questionmark, hash) -> ctll::push<ctll::anything, comment_body>;
	static constexpr auto rule(block_questionmark, C) -> ctll::push<ctll::anything, callout_kind>;
	static constexpr auto rule(block_questionmark, num) -> ctll::push<number, make_subroutine_call, close>;
	static constexpr auto rule(block_questionmark, minus) -> ctll::push<ctll::anything, number, make_subroutine_call_behind, close>;
	static constexpr auto rule(block_questionmark, plus) -> ctll::push<ctll::anything, number, make_subroutine_call_ahead, close>;
	static constexpr auto rule(block_questionmark, ampersand) -> ctll::push<ctll::anything, block_name, make_subroutine_call_with_name, close>;
	static constexpr auto rule(block_questionmark, open) -> ctll::push<ctll::anything, reset_capture, condition>;

	static constexpr auto rule(block, set_3) -> ctll::push<content_in_capture, make_capture, close>;
	static constexpr auto rule(block, _others) -> ctll::push<content_in_capture, make_capture, close>;
	static constexpr auto rule(block, questionmark) -> ctll::push<ctll::anything, block_questionmark>;

	static constexpr auto rule(comment_body, close) -> ctll::push<comment_chars_anon, close, make_comment>;
	static constexpr auto rule(comment_body, comment_chars) -> ctll::push<comment_chars_anon, close, make_comment>;

	static constexpr auto rule(callout_kind, close) -> ctll::push<ctll::anything, make_callout>;
	static constexpr auto rule(callout_kind, num) -> ctll::push<number, make_callout_numbered, close>;
	static constexpr auto rule(callout_kind, doublequote) -> ctll::push<ctll::anything, callout_dq_chars, push_name, callout_dq_chars_push_name_anon, doublequote, make_callout_named, close>;
	static constexpr auto rule(callout_kind, apostrophe) -> ctll::push<ctll::anything, callout_sq_chars, push_name, callout_sq_chars_push_name_anon, apostrophe, make_callout_named, close>;

	static constexpr auto rule(condition_questionmark_angle_open, equal_sign) -> ctll::push<ctll::anything, start_lookbehind_positive, content_in_capture, look_finish, close, condition_branches>;
	static constexpr auto rule(condition_questionmark_angle_open, exclamation_mark) -> ctll::push<ctll::anything, start_lookbehind_negative, content_in_capture, look_finish, close, condition_branches>;

	static constexpr auto rule(condition_questionmark, equal_sign) -> ctll::push<ctll::anything, start_lookahead_positive, content_in_capture, look_finish, close, condition_branches>;
	static constexpr auto rule(condition_questionmark, exclamation_mark) -> ctll::push<ctll::anything, start_lookahead_negative, content_in_capture, look_finish, close, condition_branches>;
	static constexpr auto rule(condition_questionmark, angle_open) -> ctll::push<ctll::anything, condition_questionmark_angle_open>;

	static constexpr auto rule(condition, num) -> ctll::push<number, make_condition_capture_ref, close, condition_branches>;
	static constexpr auto rule(condition, minus) -> ctll::push<ctll::anything, number, make_condition_capture_ref_behind, close, condition_branches>;
	static constexpr auto rule(condition, plus) -> ctll::push<ctll::anything, number, make_condition_capture_ref_ahead, close, condition_branches>;
	static constexpr auto rule(condition, angle_open) -> ctll::push<ctll::anything, block_name, angle_close, close, condition_branches>;
	static constexpr auto rule(condition, apostrophe) -> ctll::push<ctll::anything, block_name, apostrophe, close, condition_branches>;
	static constexpr auto rule(condition, alpha_characters) -> ctll::push<block_name, close, condition_branches>;
	static constexpr auto rule(condition, questionmark) -> ctll::push<ctll::anything, condition_questionmark>;

	static constexpr auto rule(condition_branches, set_3) -> ctll::push<condition_branch, condition_branches_end>;
	static constexpr auto rule(condition_branches, _others) -> ctll::push<condition_branch, condition_branches_end>;

	static constexpr auto rule(condition_branch, set_1) -> ctll::push<string_in_capture>;
	static constexpr auto rule(condition_branch, _others) -> ctll::push<string_in_capture>;
	static constexpr auto rule(condition_branch, close__pipe) -> ctll::push<push_empty>;

	static constexpr auto rule(condition_branches_end, close) -> ctll::push<ctll::anything, make_conditional_one>;
	static constexpr auto rule(condition_branches_end, pipe) -> ctll::push<ctll::anything, condition_branch, close, make_conditional_two>;

	static constexpr auto rule(block_name, alpha_characters) -> ctll::push<ctll::anything, push_name, alphanum_characters_push_name_anon>;

	static constexpr auto rule(mode_switch, i) -> ctll::push<ctll::anything, mode_case_insensitive, mode_switch2>;
	static constexpr auto rule(mode_switch, c) -> ctll::push<ctll::anything, mode_case_sensitive, mode_switch2>;
	static constexpr auto rule(mode_switch, s) -> ctll::push<ctll::anything, mode_singleline, mode_switch2>;
	static constexpr auto rule(mode_switch, m) -> ctll::push<ctll::anything, mode_multiline, mode_switch2>;

	static constexpr auto rule(mode_switch2, close) -> ctll::push<ctll::anything>;
	static constexpr auto rule(mode_switch2, c__i__m__s) -> ctll::push<mode_switch>;

	static constexpr auto rule(character_class_sopen, set_4) -> ctll::push<set, set_make, sclose>;
	static constexpr auto rule(character_class_sopen, _others) -> ctll::push<set, set_make, sclose>;
	static constexpr auto rule(character_class_sopen, caret) -> ctll::push<ctll::anything, set2a, set_make_negative, sclose>;

	static constexpr auto rule(character_class, sopen) -> ctll::push<ctll::anything, character_class_sopen>;

	static constexpr auto rule(set, set_4) -> ctll::push<setitem, set_start, set2b>;
	static constexpr auto rule(set, _others) -> ctll::push<setitem, set_start, set2b>;

	static constexpr auto rule(set2a, set_5) -> ctll::push<setitem2, set_start, set2b>;
	static constexpr auto rule(set2a, _others) -> ctll::push<setitem2, set_start, set2b>;
	static constexpr auto rule(set2a, sclose) -> ctll::push<set_empty>;

	static constexpr auto rule(set2b, set_5) -> ctll::push<setitem2, set_combine, set2b>;
	static constexpr auto rule(set2b, _others) -> ctll::push<setitem2, set_combine, set2b>;
	static constexpr auto rule(set2b, sclose) -> ctll::epsilon;

	static constexpr auto rule(class_named_sopen_colon, a__b__c__d__g__l__p__s__u__w__x) -> ctll::push<class_named_name, colon, sclose>;
	static constexpr auto rule(class_named_sopen_colon, caret) -> ctll::push<ctll::anything, class_named_name, negate_class_named, colon, sclose>;

	static constexpr auto rule(class_named_sopen, colon) -> ctll::push<ctll::anything, class_named_sopen_colon>;

	static constexpr auto rule(class_named, sopen) -> ctll::push<ctll::anything, class_named_sopen>;

	static constexpr auto rule(class_named_name_a_l, n) -> ctll::push<ctll::anything, u, m, class_named_alnum>;
	static constexpr auto rule(class_named_name_a_l, p) -> ctll::push<ctll::anything, h, a, class_named_alpha>;

	static constexpr auto rule(class_named_name_a, l) -> ctll::push<ctll::anything, class_named_name_a_l>;
	static constexpr auto rule(class_named_name_a, s) -> ctll::push<ctll::anything, c, i, i, class_named_ascii>;

	static constexpr auto rule(class_named_name_p, r) -> ctll::push<ctll::anything, i, n, t, class_named_print>;
	static constexpr auto rule(class_named_name_p, u) -> ctll::push<ctll::anything, n, c, t, class_named_punct>;

	static constexpr auto rule(class_named_name, a) -> ctll::push<ctll::anything, class_named_name_a>;
	static constexpr auto rule(class_named_name, b) -> ctll::push<ctll::anything, l, a, n, k, class_named_blank>;
	static constexpr auto rule(class_named_name, c) -> ctll::push<ctll::anything, n, t, r, l, class_named_cntrl>;
	static constexpr auto rule(class_named_name, d) -> ctll::push<ctll::anything, i, g, i, t, class_named_digit>;
	static constexpr auto rule(class_named_name, g) -> ctll::push<ctll::anything, r, a, p, h, class_named_graph>;
	static constexpr auto rule(class_named_name, l) -> ctll::push<ctll::anything, o, w, e, r, class_named_lower>;
	static constexpr auto rule(class_named_name, p) -> ctll::push<ctll::anything, class_named_name_p>;
	static constexpr auto rule(class_named_name, s) -> ctll::push<ctll::anything, p, a, c, e, class_named_space>;
	static constexpr auto rule(class_named_name, u) -> ctll::push<ctll::anything, p, p, e, r, class_named_upper>;
	static constexpr auto rule(class_named_name, w) -> ctll::push<ctll::anything, o, r, d, class_named_word>;
	static constexpr auto rule(class_named_name, x) -> ctll::push<ctll::anything, d, i, g, i, t, class_named_xdigit>;

	static constexpr auto rule(setitem_backslash, set_6) -> ctll::push<backslash_range, range>;
	static constexpr auto rule(setitem_backslash, D__H__N__P__S__V__W__d__h__p__s__v__w) -> ctll::push<backslash_set>;

	static constexpr auto rule(setitem, set_7) -> ctll::push<ctll::anything, push_character, range>;
	static constexpr auto rule(setitem, _others) -> ctll::push<ctll::anything, push_character, range>;
	static constexpr auto rule(setitem, sopen) -> ctll::push<class_named, range>;
	static constexpr auto rule(setitem, backslash_) -> ctll::push<ctll::anything, setitem_backslash>;

	static constexpr auto rule(setitem2_backslash, set_6) -> ctll::push<backslash_range, range>;
	static constexpr auto rule(setitem2_backslash, D__H__N__P__S__V__W__d__h__p__s__v__w) -> ctll::push<backslash_set>;

	static constexpr auto rule(setitem2, set_8) -> ctll::push<ctll::anything, push_character, range>;
	static constexpr auto rule(setitem2, _others) -> ctll::push<ctll::anything, push_character, range>;
	static constexpr auto rule(setitem2, sopen) -> ctll::push<class_named, range>;
	static constexpr auto rule(setitem2, backslash_) -> ctll::push<ctll::anything, setitem2_backslash>;

	static constexpr auto rule(range_minus, set_8) -> ctll::push<ctll::anything, push_character, make_range>;
	static constexpr auto rule(range_minus, _others) -> ctll::push<ctll::anything, push_character, make_range>;
	static constexpr auto rule(range_minus, backslash_) -> ctll::push<ctll::anything, backslash_range, make_range>;

	static constexpr auto rule(range, set_9) -> ctll::epsilon;
	static constexpr auto rule(range, _others) -> ctll::epsilon;
	static constexpr auto rule(range, minus) -> ctll::push<ctll::anything, range_minus>;

	static constexpr auto rule(backslash_range_u, hexdec) -> ctll::push<create_hexdec, ctll::anything, push_hexdec, hexdec, push_hexdec, hexdec, push_hexdec, hexdec, push_hexdec, finish_hexdec>;
	static constexpr auto rule(backslash_range_u, copen) -> ctll::push<create_hexdec, ctll::anything, hexdec, push_hexdec, hexdec_push_hexdec_anon, cclose, finish_hexdec>;

	static constexpr auto rule(backslash_range_x, hexdec) -> ctll::push<create_hexdec, ctll::anything, push_hexdec, hexdec, push_hexdec, finish_hexdec>;
	static constexpr auto rule(backslash_range_x, copen) -> ctll::push<create_hexdec, ctll::anything, hexdec, push_hexdec, hexdec_push_hexdec_anon, cclose, finish_hexdec>;

	static constexpr auto rule(backslash_range_c, set_10) -> ctll::push<ctll::anything, make_control_character>;

	static constexpr auto rule(backslash_range, set_11) -> ctll::push<ctll::anything, push_character>;
	static constexpr auto rule(backslash_range, u) -> ctll::push<ctll::anything, backslash_range_u>;
	static constexpr auto rule(backslash_range, x) -> ctll::push<ctll::anything, backslash_range_x>;
	static constexpr auto rule(backslash_range, n) -> ctll::push<ctll::anything, push_character_newline>;
	static constexpr auto rule(backslash_range, t) -> ctll::push<ctll::anything, push_character_tab>;
	static constexpr auto rule(backslash_range, r) -> ctll::push<ctll::anything, push_character_return_carriage>;
	static constexpr auto rule(backslash_range, a) -> ctll::push<ctll::anything, push_character_alarm>;
	static constexpr auto rule(backslash_range, o) -> ctll::push<ctll::anything, create_hexdec, copen, octal, push_octal, octal_push_octal_anon, cclose, finish_hexdec>;
	static constexpr auto rule(backslash_range, d0) -> ctll::push<ctll::anything, create_hexdec, octal_suffix>;
	static constexpr auto rule(backslash_range, c) -> ctll::push<ctll::anything, backslash_range_c>;
	static constexpr auto rule(backslash_range, e) -> ctll::push<ctll::anything, push_character_escape>;
	static constexpr auto rule(backslash_range, f) -> ctll::push<ctll::anything, push_character_formfeed>;

	static constexpr auto rule(octal_suffix, octal) -> ctll::push<ctll::anything, push_octal, octal_suffix2>;
	static constexpr auto rule(octal_suffix, set_12) -> ctll::push<finish_hexdec>;
	static constexpr auto rule(octal_suffix, ctll::epsilon) -> ctll::push<finish_hexdec>;
	static constexpr auto rule(octal_suffix, _others) -> ctll::push<finish_hexdec>;

	static constexpr auto rule(octal_suffix2, octal) -> ctll::push<ctll::anything, push_octal, finish_hexdec>;
	static constexpr auto rule(octal_suffix2, set_12) -> ctll::push<finish_hexdec>;
	static constexpr auto rule(octal_suffix2, ctll::epsilon) -> ctll::push<finish_hexdec>;
	static constexpr auto rule(octal_suffix2, _others) -> ctll::push<finish_hexdec>;

	static constexpr auto rule(backslash_set, d) -> ctll::push<ctll::anything, class_digit>;
	static constexpr auto rule(backslash_set, D) -> ctll::push<ctll::anything, class_nondigit>;
	static constexpr auto rule(backslash_set, w) -> ctll::push<ctll::anything, class_word>;
	static constexpr auto rule(backslash_set, W) -> ctll::push<ctll::anything, class_nonword>;
	static constexpr auto rule(backslash_set, N) -> ctll::push<ctll::anything, class_nonnewline>;
	static constexpr auto rule(backslash_set, s) -> ctll::push<ctll::anything, class_space>;
	static constexpr auto rule(backslash_set, S_) -> ctll::push<ctll::anything, class_nonspace>;
	static constexpr auto rule(backslash_set, v) -> ctll::push<ctll::anything, class_vertical_space>;
	static constexpr auto rule(backslash_set, V) -> ctll::push<ctll::anything, class_non_vertical_space>;
	static constexpr auto rule(backslash_set, h) -> ctll::push<ctll::anything, class_horizontal_space>;
	static constexpr auto rule(backslash_set, H) -> ctll::push<ctll::anything, class_non_horizontal_space>;
	static constexpr auto rule(backslash_set, p) -> ctll::push<ctll::anything, copen, property_name, cclose, make_property>;
	static constexpr auto rule(backslash_set, P) -> ctll::push<ctll::anything, copen, property_name, cclose, make_property_negative>;

	static constexpr auto rule(backslash_g_copen, minus) -> ctll::push<ctll::anything, number, cclose, make_relative_back_reference>;
	static constexpr auto rule(backslash_g_copen, num) -> ctll::push<number, cclose, make_back_reference>;
	static constexpr auto rule(backslash_g_copen, alpha_characters) -> ctll::push<block_name, cclose, make_back_reference>;

	static constexpr auto rule(backslash_g_angle_open, num) -> ctll::push<number, make_subroutine_call, angle_close>;
	static constexpr auto rule(backslash_g_angle_open, alpha_characters) -> ctll::push<block_name, make_subroutine_call_with_name, angle_close>;

	static constexpr auto rule(backslash_g_apostrophe, num) -> ctll::push<number, make_subroutine_call, apostrophe>;
	static constexpr auto rule(backslash_g_apostrophe, alpha_characters) -> ctll::push<block_name, make_subroutine_call_with_name, apostrophe>;

	static constexpr auto rule(backslash_g, copen) -> ctll::push<ctll::anything, backslash_g_copen>;
	static constexpr auto rule(backslash_g, angle_open) -> ctll::push<ctll::anything, backslash_g_angle_open>;
	static constexpr auto rule(backslash_g, apostrophe) -> ctll::push<ctll::anything, backslash_g_apostrophe>;

	static constexpr auto rule(backslash, A) -> ctll::push<ctll::anything, push_assert_subject_begin>;
	static constexpr auto rule(backslash, z) -> ctll::push<ctll::anything, push_assert_subject_end>;
	static constexpr auto rule(backslash, Z) -> ctll::push<ctll::anything, push_assert_subject_end_with_lineend>;
	static constexpr auto rule(backslash, b) -> ctll::push<ctll::anything, push_word_boundary>;
	static constexpr auto rule(backslash, B) -> ctll::push<ctll::anything, push_not_word_boundary>;
	static constexpr auto rule(backslash, K) -> ctll::push<ctll::anything, push_match_point_reset>;
	static constexpr auto rule(backslash, X) -> ctll::push<ctll::anything, make_grapheme_cluster>;
	static constexpr auto rule(backslash, set_6) -> ctll::push<backslash_range>;
	static constexpr auto rule(backslash, D__H__N__P__S__V__W__d__h__p__s__v__w) -> ctll::push<backslash_set>;
	static constexpr auto rule(backslash, g) -> ctll::push<ctll::anything, backslash_g>;
	static constexpr auto rule(backslash, escape_backreference) -> ctll::push<ctll::anything, create_number, make_back_reference>;

	static constexpr auto rule(property_name, dot__alphanum_characters) -> ctll::push<ctll::anything, push_property_name, property_name2>;

	static constexpr auto rule(property_name2, dot__alphanum_characters) -> ctll::push<ctll::anything, push_property_name, property_name2>;
	static constexpr auto rule(property_name2, equal_sign) -> ctll::push<ctll::anything, property_value>;
	static constexpr auto rule(property_name2, cclose) -> ctll::epsilon;

	static constexpr auto rule(property_value, dot__alphanum_characters) -> ctll::push<ctll::anything, push_property_value, set_push_property_value_anon>;

	static constexpr auto rule(character, set_13) -> ctll::push<ctll::anything, push_character>;
	static constexpr auto rule(character, _others) -> ctll::push<ctll::anything, push_character>;
	static constexpr auto rule(character, dot) -> ctll::push<ctll::anything, push_character_anything>;
	static constexpr auto rule(character, backslash_) -> ctll::push<ctll::anything, backslash>;

	static constexpr auto rule(character_in_capture, set_2) -> ctll::push<character>;
	static constexpr auto rule(character_in_capture, _others) -> ctll::push<character>;

	static constexpr auto rule(asserts, caret) -> ctll::push<ctll::anything, push_assert_begin>;
	static constexpr auto rule(asserts, dolar) -> ctll::push<ctll::anything, push_assert_end>;

	static constexpr auto rule(num_push_number_anon, num) -> ctll::push<ctll::anything, push_number, num_push_number_anon>;
	static constexpr auto rule(num_push_number_anon, quote__close__comma__angle_close__cclose) -> ctll::epsilon;

	static constexpr auto rule(comment_chars_anon, comment_chars) -> ctll::push<ctll::anything, comment_chars_anon>;
	static constexpr auto rule(comment_chars_anon, close) -> ctll::epsilon;

	static constexpr auto rule(callout_dq_chars_push_name_anon, callout_dq_chars) -> ctll::push<ctll::anything, push_name, callout_dq_chars_push_name_anon>;
	static constexpr auto rule(callout_dq_chars_push_name_anon, doublequote) -> ctll::epsilon;

	static constexpr auto rule(callout_sq_chars_push_name_anon, callout_sq_chars) -> ctll::push<ctll::anything, push_name, callout_sq_chars_push_name_anon>;
	static constexpr auto rule(callout_sq_chars_push_name_anon, apostrophe) -> ctll::epsilon;

	static constexpr auto rule(alphanum_characters_push_name_anon, alphanum_characters) -> ctll::push<ctll::anything, push_name, alphanum_characters_push_name_anon>;
	static constexpr auto rule(alphanum_characters_push_name_anon, quote__close__angle_close__cclose) -> ctll::epsilon;

	static constexpr auto rule(hexdec_push_hexdec_anon, hexdec) -> ctll::push<ctll::anything, push_hexdec, hexdec_push_hexdec_anon>;
	static constexpr auto rule(hexdec_push_hexdec_anon, cclose) -> ctll::epsilon;

	static constexpr auto rule(octal_push_octal_anon, octal) -> ctll::push<ctll::anything, push_octal, octal_push_octal_anon>;
	static constexpr auto rule(octal_push_octal_anon, cclose) -> ctll::epsilon;

	static constexpr auto rule(set_push_property_value_anon, dot__alphanum_characters) -> ctll::push<ctll::anything, push_property_value, set_push_property_value_anon>;
	static constexpr auto rule(set_push_property_value_anon, cclose) -> ctll::epsilon;

};

}

#endif //CTRE__PCRE__HPP
